version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Adiciona um healthcheck para garantir que o banco está pronto
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: my_nestjs_app
    restart: on-failure  # Evita loop infinito se houver erro
    depends_on:
      postgres:
        condition: service_healthy  # Aguarda PostgreSQL estar pronto
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydatabase  # Nome do banco corrigido
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./src:/app/src  # Mantém apenas o código sincronizado
      - /app/node_modules  # Garante que node_modules do container não seja sobrescrito

volumes:
  postgres_data:
